### ISSUE TITLE
Add matrix room for realtime chat

### ISSUE THREAD

**Issue by DanielG** [OpenRTX/openrtx.github.io#9]
Hi,

Discord as a chat platform for software projects [isn't](https://drewdevault.com/2021/12/28/Dont-use-Discord-for-FOSS.html), [exactly](https://sneak.berlin/20200220/discord-is-not-an-acceptable-choice-for-free-software-projects/), [popular](https://stallman.org/discord.html) with many free software developers such as myself, being a data-guzzling, privacy-violating platform with an [extremely overzealous TOS](https://tosdr.org/en/service/536) while mandating the use of proprietary software.

IMO it would be nice to at least have an official matrix room for OpenRTX that's bridged to Discord so one at least does not have to interact with their software or servers directly.

The M17 project appears to use the https://t2bot.io/discord/ service for this purpose which seems to work pretty well and seems pretty easy to set up. I'd be happy to help with the matrix aspects if needed.

--Daniel

**Comment by Nimayer** [comment]
Hi @DanielG,
Thank you for opening the issue.
The team and I agree with the point you are making.
We discussed internally about moving gradually away from Discord, and your proposal adds value to this idea.

We are now evaluating whether to create an OpenRTX Matrix Space on matrix.org or on a selfhosted homeserver, \
Do you have a suggestion for this choice?

I will keep you posted with the progress on this.

**Comment by DanielG** [comment]
That's great to hear.

Rooms/spaces in matrix being distributed it is my understanding that it doesn't actually matter too much where you create one it can always be moved by creating a name/reference for it on another homeserver if needed. In fact multiple such names can point to the same underlying room/space.

**Comment by Nimayer** [comment]
Hi @DanielG,
I created an OpenRTX Matrix space on matrix.org, and bridged the Matrix and Discord servers using the bot you suggested (https://t2bot.io/discord/).
I replicated all the Discord text channels and the bridge bot is working great!

We now consider Matrix our __official community chat platform__, and we updated [our website](https://openrtx.org/#/get_in_touch) and [Twitter profile](https://twitter.com/OpenRtx) to reflect that.

Here is the [invite link](https://matrix.to/#/#openrtx:matrix.org).

**Comment by DanielG** [comment]
Great news, already joined. Thanks!

**Comment by Nimayer** [comment]
Nice, see you there.
Closing the issue.
